INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_ANTENNAPATTERN antennapattern)

FIND_PATH(
    ANTENNAPATTERN_INCLUDE_DIRS
    NAMES antennapattern/api.h
    HINTS $ENV{ANTENNAPATTERN_DIR}/include
        ${PC_ANTENNAPATTERN_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    ANTENNAPATTERN_LIBRARIES
    NAMES gnuradio-antennapattern
    HINTS $ENV{ANTENNAPATTERN_DIR}/lib
        ${PC_ANTENNAPATTERN_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ANTENNAPATTERN DEFAULT_MSG ANTENNAPATTERN_LIBRARIES ANTENNAPATTERN_INCLUDE_DIRS)
MARK_AS_ADVANCED(ANTENNAPATTERN_LIBRARIES ANTENNAPATTERN_INCLUDE_DIRS)

